### ISSUE TITLE
Database closed after first query in GCAM-run batch query

### ISSUE THREAD

**Issue by rjplevin** [JGCRI/modelinterface#4]
Pralit has already identified this bug; I'm adding this issue at his request. 

For others that might run into this: When GCAM is configured (via XMLDB.properties) to run a batch query before exiting -- whether using the in-memory or on-disk database -- the database is closed after the first query in the batch file, causing all subsequent queries to fail. Queries executed via ModelInterface against an on-disk database, after GCAM exits, work properly.

**Comment by pralitp** [comment]
Turns out it wasn't so complicated to get this right.
